name: Docker Action Workflow
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Run Action
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

