on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world action step
        uses: actions/hello-world-docker-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
